steps:
  # Build Docker image
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/lokaler.kaufen.build-container", "."]

images: ["gcr.io/$PROJECT_ID/lokaler.kaufen.build-container"]